"""0004_m3_memory_kb_attachment

Revision ID: 57d22824e0e5
Revises: 58ff6088852e
Create Date: 2026-08-15 13:54:11.983023

M3：pgvector 扩展 + 记忆三表 + 知识库三表 + 附件表。
手写重点：GENERATED tsvector 列（CJK 逐字插空格 → unigram）、HNSW/GIN 索引、UNIQUE 约束。
注意 CJK 正则必须 raw string（普通字符串会被 Python 预编译成汉字）。
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57d22824e0e5'
down_revision: Union[str, None] = '58ff6088852e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBED_DIM = 1024
CJK_SPACE = r"([一-鿿])"  # 中文字符逐字插空格（raw string 必须）


def _tsv_expr() -> str:
    """GENERATED 列表达式：CJK 逐字插空格后 simple 分词（无中文分词扩展的 BM25 方案）。"""
    return (
        "to_tsvector('simple', regexp_replace(content, '"
        + CJK_SPACE
        + "', '\\1 ', 'g'))"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ---- 记忆 ----
    op.create_table(
        "memory_trace",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), sa.ForeignKey("conversations.id"), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index(op.f("ix_memory_trace_user_id"), "memory_trace", ["user_id"], unique=False)

    op.create_table(
        "longterm_memory",
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("card_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_longterm_memory_user_id"), "longterm_memory", ["user_id"], unique=False)

    op.create_table(
        "longterm_memory_version",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("memory_id", sa.UUID(), sa.ForeignKey("longterm_memory.id"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("memory_id", "version", name="uniq_longterm_memory_version"),
    )

    # ---- 知识库 ----
    op.create_table(
        "kb_collections",
        sa.Column("org_id", sa.UUID(), sa.ForeignKey("orgs.id"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_kb_collections_org_id"), "kb_collections", ["org_id"], unique=False)

    op.create_table(
        "kb_documents",
        sa.Column("collection_id", sa.UUID(), sa.ForeignKey("kb_collections.id"), nullable=False),
        sa.Column("org_id", sa.UUID(), sa.ForeignKey("orgs.id"), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_kb_documents_collection_id"), "kb_documents", ["collection_id"], unique=False)
    op.create_index(op.f("ix_kb_documents_org_id"), "kb_documents", ["org_id"], unique=False)

    op.create_table(
        "kb_chunks",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("kb_documents.id"), nullable=False),
        sa.Column("collection_id", sa.UUID(), sa.ForeignKey("kb_collections.id"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBED_DIM), nullable=True),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(_tsv_expr(), persisted=True),
            nullable=False,
        ),
        sa.UniqueConstraint("document_id", "chunk_index", name="uniq_kb_chunks_doc_idx"),
    )
    op.create_index(op.f("ix_kb_chunks_collection_id"), "kb_chunks", ["collection_id"], unique=False)
    op.create_index(op.f("ix_kb_chunks_org_id"), "kb_chunks", ["org_id"], unique=False)
    # HNSW 向量索引（余弦距离；空表建索引瞬间完成，表大后改 CREATE INDEX CONCURRENTLY 的接缝）
    op.execute(
        f"CREATE INDEX ix_kb_chunks_embedding_hnsw ON kb_chunks "
        f"USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    # GIN tsvector 索引（BM25 通道）
    op.execute("CREATE INDEX ix_kb_chunks_content_tsv_gin ON kb_chunks USING gin (content_tsv)")

    # ---- 附件 ----
    op.create_table(
        "attachments",
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), sa.ForeignKey("conversations.id"), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_attachments_user_id"), "attachments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_user_id"), table_name="attachments")
    op.drop_table("attachments")
    op.execute("DROP INDEX IF EXISTS ix_kb_chunks_content_tsv_gin")
    op.execute("DROP INDEX IF EXISTS ix_kb_chunks_embedding_hnsw")
    op.drop_index(op.f("ix_kb_chunks_org_id"), table_name="kb_chunks")
    op.drop_index(op.f("ix_kb_chunks_collection_id"), table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_kb_documents_org_id"), table_name="kb_documents")
    op.drop_index(op.f("ix_kb_documents_collection_id"), table_name="kb_documents")
    op.drop_table("kb_documents")
    op.drop_index(op.f("ix_kb_collections_org_id"), table_name="kb_collections")
    op.drop_table("kb_collections")
    op.drop_table("longterm_memory_version")
    op.drop_index(op.f("ix_longterm_memory_user_id"), table_name="longterm_memory")
    op.drop_table("longterm_memory")
    op.drop_index(op.f("ix_memory_trace_user_id"), table_name="memory_trace")
    op.drop_table("memory_trace")
    # extension 不 drop（幂等；其他环境可能共享）
    # ### end Alembic commands ###
