"""0003_mcp_tool_name

Revision ID: 58ff6088852e
Revises: 0066b760bf5b
Create Date: 2026-08-14 22:31:06.319467

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ff6088852e'
down_revision: Union[str, None] = '0066b760bf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MCP 原始工具名（注册时捕获，启动重建 spec 时透传给 call_tool；slug 名会失真）
    op.add_column("tool_definitions", sa.Column("mcp_tool_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_definitions", "mcp_tool_name")
    # ### end Alembic commands ###
